# Generated by Django 3.0 on 2019-12-10 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprego',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publisher', models.CharField(blank=True, max_length=20)),
                ('location', models.IntegerField(choices=[(1, 'Aveiro'), (2, 'Viseu'), (3, 'Porto'), (4, 'Guarda'), (5, 'Bragança'), (6, 'Vila Real'), (7, 'Braga'), (8, 'Viana do Castelo'), (9, 'Coimbra'), (10, 'Castelo Branco'), (11, 'Leiria'), (12, 'Santarém'), (13, 'Portalegre'), (14, 'Lisboa'), (15, 'Évora'), (16, 'Setubal'), (17, 'Beja'), (18, 'Faro')])),
                ('job_sector', models.IntegerField(choices=[(1, 'Software Development'), (2, 'Analyst'), (3, 'Project Management'), (4, 'Sales'), (5, 'Administrative'), (6, 'Finance'), (7, 'Art/Design'), (8, 'Human Resources'), (9, 'Medical/Healthcare'), (10, 'Cashier')])),
                ('file', models.FileField(blank=True, upload_to='')),
            ],
            options={
                'db_table': 'emprego',
            },
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('b_date', models.DateField()),
                ('curriculum', models.FileField(upload_to='')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('website', models.URLField()),
                ('sector', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'utilizador',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('website', models.URLField()),
                ('company_name', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
    ]
