# Generated by Django 3.0 on 2019-12-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobber_restapi_app', '0002_auto_20191216_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprego',
            name='file',
        ),
        migrations.RemoveField(
            model_name='emprego',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='user',
        ),
        migrations.AddField(
            model_name='empresa',
            name='job_sector',
            field=models.IntegerField(choices=[(1, 'Software Development'), (2, 'Analyst'), (3, 'Project Management'), (4, 'Sales'), (5, 'Administrative'), (6, 'Finance'), (7, 'Art/Design'), (8, 'Human Resources'), (9, 'Medical/Healthcare'), (10, 'Cashier')], default=1),
        ),
        migrations.AlterField(
            model_name='emprego',
            name='job_sector',
            field=models.IntegerField(choices=[(1, 'Software Development'), (2, 'Analyst'), (3, 'Project Management'), (4, 'Sales'), (5, 'Administrative'), (6, 'Finance'), (7, 'Art/Design'), (8, 'Human Resources'), (9, 'Medical/Healthcare'), (10, 'Cashier')], default=1),
        ),
        migrations.AlterField(
            model_name='emprego',
            name='location',
            field=models.IntegerField(choices=[(1, 'Aveiro'), (2, 'Viseu'), (3, 'Porto'), (4, 'Guarda'), (5, 'Bragança'), (6, 'Vila Real'), (7, 'Braga'), (8, 'Viana do Castelo'), (9, 'Coimbra'), (10, 'Castelo Branco'), (11, 'Leiria'), (12, 'Santarém'), (13, 'Portalegre'), (14, 'Lisboa'), (15, 'Évora'), (16, 'Setubal'), (17, 'Beja'), (18, 'Faro')], default=1),
        ),
    ]
